# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7204175a8b07bfba279dba0cf88e8a9f36946f03706140075cbd030ce1d24390efda0d3334e70bd09733e916d4215134364f98d1ebcdaa8838984fd91fed7175
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  
test:
  secret_key_base: c5ee3a1a2a7a65dd0f53b39cafab777489d3dd6c252ff9256fd8e3a66b36dac01a663fbc88037d4e4686a46c1aca0259f6a78e1cc9dac8fdb6fc05d0b7eadf17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
